name: ðŸš€ Deploy to Host

on:
  workflow_run:
    workflows: ["ðŸ³ Containers"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible and Ansible POSIX extension
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-galaxy collection install ansible.posix

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create inventory file
        env:
          HOST_IP: ${{ secrets.HOST_IP }}
        run: |
          echo "$HOST_IP ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa" > inventory.ini

      - name: Deploy with Ansible
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i inventory.ini ./ansible/service.yml

      - name: Clean up SSH key
        if: always()
        run: rm -f ~/.ssh/id_rsa